export const VALIDATION_STATUS = {
  SUCCESS: 'SUCCESS',
  ERROR: 'ERROR'
} as const

export const LOGIN_ACTION_TYPE = {
  SET_EMAIL_ERROR: 'SET_EMAIL_ERROR',
  SET_PASSWORD_ERROR: 'SET_PASSWORD_ERROR',
  SET_NOMBRE_ERROR: 'SET_NOMBRE_ERROR',
  SET_EMAIL_VALUE: 'SET_EMAIL_VALUE',
  SET_PASSWORD_VALUE: 'SET_PASSWORD_VALUE'
} as const